id: P49547776
initial_creation_type: ocr
source_metadata:
  volumes:
    2cc0b9e1eb724e6c9a0e9904f34a4a4d:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: ''
      total_pages: 1201
      volume_number: 46
